AllCops:
  TargetRubyVersion: 3.3.5
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'spec/cassettes/**/*'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: true