AllCops:
  TargetRubyVersion: 3.3.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'spec/cassettes/**/*'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 60

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 45
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: true